name: CI-version

on:
  push:
    tags:
      - "v*"

env:
  CARGO_TERM_COLOR: always
  
jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        toolchain:
          - stable
          - nightly
        features:
          -
          - --no-default-features --features Debug
          - --no-default-features --features Clone
          - --no-default-features --features Copy
          - --no-default-features --features Clone --features Copy
          - --no-default-features --features PartialEq
          - --no-default-features --features Eq
          - --no-default-features --features PartialEq --features Eq
          - --no-default-features --features PartialOrd
          - --no-default-features --features Ord
          - --no-default-features --features PartialOrd --features Ord
          - --no-default-features --features Hash
          - --no-default-features --features Default
          - --no-default-features --features Deref
          - --no-default-features --features DerefMut
          - --no-default-features --features Deref --features DerefMut
          - --no-default-features --features Into
    name: Test ${{ matrix.toolchain }} on ${{ matrix.os }} (${{ matrix.features }})
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
      - run: cargo test --release ${{ matrix.features }}
      - run: cargo doc --release ${{ matrix.features }}

  MSRV:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        toolchain:
          - "1.60"
        features:
          -
          - --no-default-features --features Debug
          - --no-default-features --features Clone
          - --no-default-features --features Copy
          - --no-default-features --features Clone --features Copy
          - --no-default-features --features PartialEq
          - --no-default-features --features Eq
          - --no-default-features --features PartialEq --features Eq
          - --no-default-features --features PartialOrd
          - --no-default-features --features Ord
          - --no-default-features --features PartialOrd --features Ord
          - --no-default-features --features Hash
          - --no-default-features --features Default
          - --no-default-features --features Deref
          - --no-default-features --features DerefMut
          - --no-default-features --features Deref --features DerefMut
          - --no-default-features --features Into
    name: Test ${{ matrix.toolchain }} on ${{ matrix.os }} (${{ matrix.features }})
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
      - run: cargo test --release --lib --bins ${{ matrix.features }}